// Next.js
import Image from 'next/image'
import Link from 'next/link'
// Styles & Images
// import styles from '../styles/Home.module.css'
import profilePic from '../public/images/me.jpg'
// External
import TypewriterComponent from 'typewriter-effect'
import { motion } from "framer-motion"
// Components
import WorkCard from '../components/workCard'
import Section from '../components/section'
import Button from '../components/button'
import { ChevronDoubleRightIcon, SunIcon } from '@heroicons/react/outline'
import { darkMode } from '../tailwind.config'
import React, { useState } from 'react'
import HeroPost from '../components/hero-post'
import MoreStories from '../components/more-stories'
import { getAllPostsForHome, getPostAndMorePosts } from './api/api'

export default function Home({ allPosts, preview }) {

  const container = {
    visible: {
      opacity: 1,
      transition: {
        when: "beforeChildren",
        staggerChildren: 0.1,
      },
    },
    hidden: {
      opacity: 0,
      transition: {
        when: "afterChildren",
      },
    },
  }

  const section = {
    visible: { opacity: 1, y: 0 },
    // visible: { opacity: 1, x: 0, y: 0 },
    hidden: { opacity: 0, y: 10 },
    // transition: { duration: 5 },
    // hidden: { opacity: 0, x: -100, y: 10 },
    // initial={{ y: 10, opacity: 0 }}
    // animate={{ y: 0, opacity: 1 }}
  }

  const heroPost = allPosts[0]
  const morePosts = allPosts.slice(0, 3)

  return (


    <div className='py-0 px-8'>
      {/* <Head>
        <title>Dylan Smith Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Arya:wght@400;700&family=Josefin+Sans:wght@300;400;700&family=Voces&display=swap" rel="stylesheet" />
      </Head> */}

      {/* <main className='bg-sky-400 min-h-[80vh] p-16 flex flex-col justify-center items-center'> */}
      <main>
        <motion.div
          initial="hidden"
          animate="visible"
          variants={container}
          transition={{ duration: 0.8 }}
          className={`flex flex-col justify-center gap-8 ${darkMode && 'dark'}`}
        >
          {/* <motion.div
            className='flex flex-col justify-center items-center mt-8'
            variants={section}
            transition={{ duration: 0.8 }}
          > */}
          <Section>
            <div class="left flex items-center gap-12 xl:gap-16">
              <div class="image-container w-40 rounded-full overflow-hidden object-contain mr-8 border-2 border-black">
                <Image
                  src={profilePic}
                  alt="Picture of Dylan Smith"
                  layout='responsive'
                  objectFit='cover'
                  width={'200px'}
                  height={'200px'}
                />
              </div>
              <div className='light flex flex-col text-primary'>
                <h1 className='text-4xl text-skin-base'>Dylan Smith</h1>
                {/* <span className=''>subtitle</span> */}
                <div className='right text-3xl flex flex-col'>
                  <TypewriterComponent
                    options={{
                      strings: ['', 'front-end developer', 'ui/uix designer', 'logo designer', 'husband', 'dad'],
                      autoStart: true,
                      loop: true,
                      delay: 'natural',
                      deleteSpeed: 'natural'
                    }}
                  />
                  <span>and lover of all things web related</span>
                  <span>based in new york</span>
                </div>
              </div>
            </div>
          </Section>
          {/* </motion.div> */}

          {/* <motion.div
            className="flex flex-col justify-center items-center text-5xl md:text-5xl 2xl:text-6xl text-skin-base"
            variants={section}
            transition={{ duration: 0.8 }}
          >
            <TypewriterComponent
              options={{
                strings: ['', 'front-end developer', 'ui/uix designer', 'logo designer', 'husband', 'dad'],
                autoStart: true,
                loop: true,
                delay: 'natural',
                deleteSpeed: 'natural'
              }}
            />
            <span>and lover of all things web related</span>
            <span>based in new york</span>
          </motion.div> */}


          <Section>
            {/* <motion.div
            className='featured-work flex flex-col items-center gap-12 p-8 text-skin-base'
            variants={section}
            transition={{ duration: 0.8 }}
          > */}
            {/* <h3 className='text-3xl'>recent stuff</h3> */}
            {/* {heroPost && (
              <HeroPost
                title={heroPost.title}
                coverImage={heroPost.coverImage}
                date={heroPost.date}
                author={heroPost.author}
                slug={heroPost.slug}
                summary={heroPost.summary}
              />
            )} */}
            {morePosts.length > 0 && <MoreStories posts={morePosts} />
            }

            {/* <button className='flex items-center gap-4 bg-skin-button-accent hover:bg-skin-button-accent-hover text-skin-inverted rounded-md p-4'>
              <Link href='/work'>
                all my work
              </Link>
              <ChevronDoubleRightIcon className='w-6' />
            </button> */}
            <div className='mt-8'>
              <Button
                bgColor='black'
                textColor='white'
              >
                <Link href='/work'>
                  all my work
                </Link>
                <ChevronDoubleRightIcon className='w-6' />
              </Button>
            </div>

            {/* </motion.div> */}
          </Section>

          {/* <motion.div
            className='text-skin-base'
            variants={section}
            transition={{ duration: 0.8 }}
          >
            follow me around the web
          </motion.div> */}

        </motion.div>
      </main >
    </div >
  )
}

export async function getStaticProps({ preview = false }) {
  const allPosts = await getAllPostsForHome(preview)
  return {
    props: { allPosts, preview },
    revalidate: 1
  }
}